# Site settings
title: monelog
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  opinions are like farts, everybody's stinks but your own.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  lostcode

# Build settings
markdown: kramdown
